### ISSUE TITLE
Deno command execution errors while validating an LHC form

### ISSUE THREAD

**Issue by Prathitha** [shah/ts-lhncbc-lforms#4]
**Observations:**
1. The command 'deno-run' did not work for me; but 'deno run' worked.
2. The deno command without version number (>deno run "https://denopkg.com/shah/ts-lhncbc-lforms/lformctl.ts" validate "**/*.json" --verbose) shows _35 errors_ while the command with version 1.1.3 (>deno run "https://denopkg.com/shah/ts-lhncbc-lforms@v1.1.3/lformctl.ts" validate "**/*.json" --verbose) shows _19 errors_ on the same LHC form JSON. The errors are like the following:

Check https://raw.githubusercontent.com/shah/ts-lhncbc-lforms/master/lformctl.ts
error: TS2339 [ERROR]: Property 'link' does not exist on type 'typeof Deno'. 'Deno.link' is an unstable API. Did you forget to run with the '--unstable' flag?
  await Deno.link(src, dest);
             ~~~~
    at https://deno.land/std@0.69.0/fs/ensure_link.ts:28:14

TS2339 [ERROR]: Property 'linkSync' does not exist on type 'typeof Deno'. 'Deno.linkSync' is an unstable API. Did you forget to run with the '--unstable' flag?
  Deno.linkSync(src, dest);
       ~~~~~~~~
    at https://deno.land/std@0.69.0/fs/ensure_link.ts:52:8

**Note:**
1. I am unable to catch out whether these errors are there in the LHC form JSON I have chosen to validate or whether the validation rules are to be set in the validator

Thanks

**Comment by shah** [comment]
This is an environmental issue with the `deno run` command. If you're not using the alias `deno-run` you _must_ use `deno run -A --unstable`.
